query RunInput {
  cart {
    cost {
      subtotalAmount {
        amount
        currencyCode
      }
    }
    billingAddress {
      city
      provinceCode
      zip
      countryCode
    }
    deliveryGroups {
      deliveryAddress {
        city
        provinceCode
        zip
        countryCode
      }
      deliveryOptions {
        handle
        title
        deliveryMethodType
        cost {
          amount
          currencyCode
        }
      }
    }
  }
  discountNode {
    metafield(namespace: "$app", key: "function-configuration") {
      jsonValue
    }
  }
  shop {
    metafield(namespace: "custom", key: "entrega_tienda_config") {
      jsonValue
    }
  }
}
