query CartDeliveryOptionsTransformRunInput {
  cart {
    billingAddress {
      city
      provinceCode
      zip
      countryCode
    }
    deliveryGroups {
      deliveryAddress {
        city
        provinceCode
        zip
        countryCode
      }
      deliveryOptions {
        handle
        title
        deliveryMethodType
        cost {
          amount
        }
      }
    }
  }
  shop {
    metafield(namespace: "$app", key: "entrega_tienda_config") {
      jsonValue
    }
  }
}
